# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - bash: echo Doing a Build
    - script: echo Build process completed

- stage: DevDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo Starting a DevDeploy
    - script: echo DevDeploy process completed
  
- stage: QADeploy
  jobs:
  - job: job1
    steps:
    - bash: echo Starting a QADeploy Job
    - script: echo QADeploy process completed
  
- stage: ProdDeploy
  jobs:
  - job: job1
    steps:
    - bash: echo Starting a ProdDeploy Job
    - script: echo ProdDeploy process completed
  