# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

#pipeline structure==> stages->Jobs->Tasks(Steps)

jobs:
- job: Job1
  steps: 
  - script: echo job1 - Hello World cahnged!
    displayName: 'Run on one-line Script'
  - script: 
      echo other script
      echo more information
    displayName: 'Run a multi-line script Job1'

- job: Job2
  steps: 
  - script: echo Job2!
  displayName: 'Run a multi-line script Job2'
          