# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Build
    variables:
    - name: stage1
      value: Buildstage

    jobs:
      - job: BuildFirstJob
        steps:
          - bash: echo Hi! this is BuildFirstJob
          - bash: echo $(stage1) variable

  - stage: Test
    variables:
      environment: Test
    jobs:
      - job: Firstjob
        steps:
        - bash: echo Hi! this is TestFirstJob
        - bash: echo $(environment) variable


  - stage: Acceptance
    variables:
      environment: Acceptance
    jobs:
      - job: Firstjob
        steps:
        - bash: echo Hi! this is AccFirstJob
        - bash: echo $(environment) variable

  - stage: Production
    variables:
      environment: Production
    jobs:
      - job: Firstjob
        steps:
        - bash: echo Hi! this is ProdFirstJob
        - bash: echo $(environment) variable
