# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build 
  jobs:
    - job: FirstJob
      steps:
      - bash: echo build FirstJob
    - job: SecondJob
      steps:
      - bash: echo build SecondJob
      
- stage: Test
  dependsOn: Build
  jobs:
    - job: TestEnvJob
      steps:
        - bash: echo build TestEnvJob

- stage: Acceptance
  dependsOn: Build
  jobs:
    - job: AccEnvJob
      steps:
      - bash: echo build AccEnvJob
    
- stage: Production
  dependsOn:
  - Test
  - Acceptance
  jobs:
  - job: ProdEnvJob
    steps:
    - bash: echo build ProdEnvJob
    



